import { Item } from "./types"

export const mockItems: Item[] = [
    {
        particulars: "test",
        size: "1x",
        hsn: "7307",
        quantity: 1,
        unit: "",
        rate: 5,
        gst: 18,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "7307",
        quantity: 1,
        unit: "",
        rate: 5,
        gst: 18,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "7307",
        quantity: 1,
        unit: "",
        rate: 5,
        gst: 18,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "7307",
        quantity: 1,
        unit: "",
        rate: 5,
        gst: 18,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "7307",
        quantity: 1,
        unit: "",
        rate: 5,
        gst: 18,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "7307",
        quantity: 1,
        unit: "",
        rate: 5,
        gst: 18,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "7307",
        quantity: 1,
        unit: "",
        rate: 5,
        gst: 18,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "7308",
        quantity: 1,
        unit: "",
        rate: 5,
        gst: 18,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "4016",
        quantity: 1,
        unit: "",
        rate: 10,
        gst: 28,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "4016",
        quantity: 1,
        unit: "",
        rate: 10,
        gst: 28,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "4016",
        quantity: 1,
        unit: "",
        rate: 10,
        gst: 28,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "4016",
        quantity: 1,
        unit: "",
        rate: 10,
        gst: 28,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "4017",
        quantity: 1,
        unit: "",
        rate: 10,
        gst: 28,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "4115",
        quantity: 1,
        unit: "",
        rate: 20,
        gst: 12,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "4115",
        quantity: 1,
        unit: "",
        rate: 20,
        gst: 12,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "4116",
        quantity: 1,
        unit: "",
        rate: 20,
        gst: 12,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "4116",
        quantity: 1,
        unit: "",
        rate: 20,
        gst: 12,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "4116",
        quantity: 1,
        unit: "",
        rate: 20,
        gst: 12,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "4116",
        quantity: 1,
        unit: "",
        rate: 20,
        gst: 12,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "4115",
        quantity: 1,
        unit: "",
        rate: 20,
        gst: 12,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "4115",
        quantity: 1,
        unit: "",
        rate: 20,
        gst: 12,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "4116",
        quantity: 1,
        unit: "",
        rate: 20,
        gst: 12,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "4116",
        quantity: 1,
        unit: "",
        rate: 20,
        gst: 12,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "4116",
        quantity: 1,
        unit: "",
        rate: 20,
        gst: 12,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "4116",
        quantity: 1,
        unit: "",
        rate: 20,
        gst: 12,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "7307",
        quantity: 1,
        unit: "",
        rate: 5,
        gst: 18,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "7307",
        quantity: 1,
        unit: "",
        rate: 5,
        gst: 18,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "7307",
        quantity: 1,
        unit: "",
        rate: 5,
        gst: 18,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "7307",
        quantity: 1,
        unit: "",
        rate: 5,
        gst: 18,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "7307",
        quantity: 1,
        unit: "",
        rate: 5,
        gst: 18,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "7307",
        quantity: 1,
        unit: "",
        rate: 5,
        gst: 18,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "7307",
        quantity: 1,
        unit: "",
        rate: 5,
        gst: 18,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "7308",
        quantity: 1,
        unit: "",
        rate: 5,
        gst: 18,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "4016",
        quantity: 1,
        unit: "",
        rate: 10,
        gst: 28,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "4016",
        quantity: 1,
        unit: "",
        rate: 10,
        gst: 28,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "4016",
        quantity: 1,
        unit: "",
        rate: 10,
        gst: 28,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "4016",
        quantity: 1,
        unit: "",
        rate: 10,
        gst: 28,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "4017",
        quantity: 1,
        unit: "",
        rate: 10,
        gst: 28,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "4115",
        quantity: 1,
        unit: "",
        rate: 20,
        gst: 12,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "4115",
        quantity: 1,
        unit: "",
        rate: 20,
        gst: 12,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "4116",
        quantity: 1,
        unit: "",
        rate: 20,
        gst: 12,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "4116",
        quantity: 1,
        unit: "",
        rate: 20,
        gst: 12,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "4116",
        quantity: 1,
        unit: "",
        rate: 20,
        gst: 12,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "4116",
        quantity: 1,
        unit: "",
        rate: 20,
        gst: 12,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "4115",
        quantity: 1,
        unit: "",
        rate: 20,
        gst: 12,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "4115",
        quantity: 1,
        unit: "",
        rate: 20,
        gst: 12,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "4116",
        quantity: 1,
        unit: "",
        rate: 20,
        gst: 12,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "4116",
        quantity: 1,
        unit: "",
        rate: 20,
        gst: 12,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "4116",
        quantity: 1,
        unit: "",
        rate: 20,
        gst: 12,
    },
    {
        particulars: "test",
        size: "1x",
        hsn: "4116",
        quantity: 1,
        unit: "",
        rate: 20,
        gst: 12,
    },
]
